# Site settings
title: Josslyn Zhang
description: Josslyn Zhang's personal website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "https://josslynz.github.io"
# User settings
username: Josslyn Zhang
user_description: I'm Josslyn Zhang, a recent graduate in Statistics, Computer Science and Mathematics. I'm currently based in Denver, Colorado and in the future I hope to work as a Data Engineer. My curiosity for search and recommendation engines drove me to work with data in academia. I've recently been experimenting with mathematical modeling and machine learning in my spare time with Python, leveraging tools such as TensorFlow. I also enjoy volunteer work, travel, street food and in the future I hope to learn surfing and diving.
user_title: Aspiring Data Engineer
email: josszhang11@gmail.com
linkedin: "josslynz"
github_username: josslynz

# Google-analytics

exclude: ['package.json', 'src' , 'node_modules']
